apiVersion: v1
baseDomain: installer.gcp.devcluster.openshift.com
metadata:
  name: bbarbach-ocp-38471
proxy:
  httpProxy: user:password@127.0.0.1:3128
  httpsProxy: ftp://user:password@127.0.0.1:3128
  noProxy: test.no-proxy.com, localhost
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: openshift-dev-installer
    region: us-west1
pullSecret: '{"auths":{"fake.registry.io":{"auth":"dGVzdDp0ZXN0"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC test@example.com'
